Repository aurora-is-near/aurora-evm, pull requests merged in 2024-07, with the labels that each got.

#48 Feat: add optimizations for U256 constant calculations and Backend operations
  core/src/eval/misc.rs
  core/src/lib.rs
  core/src/memory.rs
  core/src/stack.rs
  core/src/utils.rs
  evm-tests/jsontests/src/state.rs
  gasometer/src/costs.rs
  runtime/src/eval/system.rs
  src/executor/stack/executor.rs
  src/executor/stack/memory.rs
  src/lib.rs
Labels: enhancement

#49 Feat: add usize casting strict check
  Cargo.toml
  core/src/error.rs
  core/src/eval/macros.rs
  core/src/eval/misc.rs
  core/src/lib.rs
  runtime/src/eval/macros.rs
  runtime/src/eval/system.rs
Labels: enhancement, tests

#50 Feat: ethereum tests v14.0
  .github/workflows/rust.yml
  Cargo.toml
  evm-tests/ethjson/src/spec/spec.rs
  evm-tests/jsontests/src/state.rs
Labels: enhancement, tests

#51 ci: add execution unit tests and eth tests on 32bit arch
  .github/workflows/rust.yml
Labels: tests, ci
